### PR TITLE
Portuguese language + Challenge card

### PR DESCRIPTION
**Pull request by EduardoSMarques**
- Prompts and responses in portuguese
-  Challenge card that winner must draw and assign completion of the challenge to another player

### CODE REVIEW

**Comment by Matthieu-z-David** [comment]
I don't speak Portuguese but It seams accurate to me, @Naopod what do you think about the new rule considering the ones you added ?

**Comment by EduardoSMarques** [comment]
> I don't speak Portuguese but It seams accurate to me, @Naopod what do you think about the new rule considering the ones you added ?

I think there is no conflict. @Naopod ?

**Comment by Naopod** [comment]
> I don't speak Portuguese but It seams accurate to me, @Naopod what do you think about the new rule considering the ones you added ?

No problem, it sounds good and adds a layer of fun. Perfect

**Comment by yunjieee** [comment]
This is a very interesting proposal! Using Portuguese prompts and responses will make our game more global and attract more Portuguese-speaking players to participate. This diversity of languages will undoubtedly increase the accessibility and inclusivity of our games!!!!!!!

**Pull request merged**
