### PR TITLE
Balance in the Card Czard Distribution

### PR DESCRIPTION
**Pull request by B4dCow**
To add balance I changed the rule about the assignment of the Card Czar

### CODE REVIEW

**Comment by ca-lida** [comment]
I dont hate it - but what about having the loser ie the worst card be the new czar?

**Review by vallathortense — APPROVED** [review]
clearer thx :)

**Review by Naopod — APPROVED** [review]
Good idea, ensures everyone will have this role, hence players all play the same amount of rounds

**Comment by mmucilam** [comment]
This is great, very insightful in terms of fluidity of play

**Comment by YurenJeremyJin** [comment]
It's similar to the rules of Texas Hold'em? Everyone gets a turn for this Card Czar role

**Review by mmucilam — APPROVED** [review]
This is great, very insightful in terms of fluidity of play

**Comment by Matthieu-z-David** [comment]
That's a nice modification of the rules, ensuring that everyone can participate as a Card Czar 👍

**Review by ca-lida — APPROVED** [review]

**Comment by yunjieee** [comment]
hello, this is a very good idea. It make this game more interesting and more people would like to join in this game!!!

**Comment by stellanweadau** [comment]
I also approval Nicolas @B4dCow 's idea.

**Pull request merged**
