### PR TITLE
Additional point for the discussion card owner

### PR DESCRIPTION
**Pull request by stellanweadau**
My idea is to reward with an extra point the discussion card owner if his/her point of view is aligned with the community one. It urges people to envy this position where you can gain points point easier. As a result, they won't submit an uninteresting topic otherwise, they will be less likely to obtain points.

PS : the 5 remaining players give only ONE point and discuss to choose to whom. If plenty players have good arguments, they must decide

### CODE REVIEW

**Review by EduardoSMarques — APPROVED** [review]
It seems a good idea

**Comment by B4dCow** [comment]
I approve this change I believe that the complexity added is worth it. 

The point of the game being to discuss about peer production related topics it seems especially relevant to add a weight to the peers opinion.

Nevertheless, in the situation where everyone votes for his or her response card, the Czar Card is the one to decide.

**Review by B4dCow — APPROVED** [review]
as commented i believe it adds to the relevance of the peer aspect of the game

**Comment by Matthieu-z-David** [comment]
This extra point adds more incentives to participants, hence demonstrating the value added of peer to peer production

**Comment by Matthieu-z-David** [comment]
This extra point adds more incentives to participants, hence demonstrating the value added of peer to peer production

**Comment by yunjieee** [comment]
Your idea is creative and could really incentivize players to submit more interesting and resonant topics. This approach increases the interactivity of the game and encourages players to think deeply and discuss various issues. It can improve the educational value and participation of the game.
Thank you for your share!!!!!

**Pull request merged**
