### PR TITLE
 Launch an anonymous poll after discussion part

### PR DESCRIPTION
**Pull request by YurenJeremyJin**
Sorry, forget to change main.tex file, last one was closed

### CODE REVIEW

**Comment by stellanweadau** [comment]
I agree with you. Setting an anonymous framework for the vote limits bias linked to the current players' score. Votes will be consequently allocated based on arguments instead of scores.
An alternative option can be to hide people score throughout the game but it would imply some strategic behaviours among players (Game Theory knowlege is required...)

**Comment by Matthieu-z-David** [comment]
@YurenJeremyJin can you look at the conflicts generated by your PR ?
After a quick check, it relates to your lines added to Readme.md and main.tex, the button resolve conflicts could be of good help

**Comment by stellanweadau** [comment]
@Matthieu-z-David the conflict is due to the fact that there were some PRs in parallel of this one (for instance mine PR #25) where README.md and main.tex were modified.

@YurenJeremyJin if you still want to do your PR, you should submit a new PR from the current project OR revolve the conflict.

**Comment by YurenJeremyJin** [comment]
I just resolved the conflict, please check the changed document

**Comment by yunjieee** [comment]
This is a very interesting discussion!  An anonymous framework for the vote or hiding people score throughout the game can make this game more sophisticated and can also make players focus on the game itself. I believe that this kind of change can bring more fun for this game and can attract more and more people joining in this game! 

By the way, adding game theory knowledge sounds really fascinating! If the game can have it, I would definitely to play it!!!!

**Pull request merged**
