### PR TITLE
Anthony's branch

### PR DESCRIPTION
**Pull request by Naopod**
**Added some rules for time limit**

- Two modes of playing : "quick-play" and "long-discussion", each with different time settings;
- Limit for a game depending on the game mode chosen
- Limit for time of discussion depending on the game mode chosen

### CODE REVIEW

**Comment by Matthieu-z-David** [comment]
That's a good idea, maybe rename it in a more fancy way : Blitz or Debate
Maybe we could add a rule for the long version with an explicit question. Could you add this ? @Naopod

**Comment by B4dCow** [comment]
Nice feature ! It will make the game more challenging

**Comment by Naopod** [comment]
> That's a good idea, maybe rename it in a more fancy way : Blitz or Debate Maybe we could add a rule for the long version with an explicit question. Could you add this ? @Naopod

Sure, what about adding one "general" leading question on each answer to lead the discussion (in case no one finds everything)

**Comment by Naopod** [comment]
I added prompts andchanged the name of gamemodes

**Review by Matthieu-z-David — APPROVED** [review]
that's nice you added the suggested modification, it really is a community production ;)

**Comment by yunjieee** [comment]
This is a very interesting proposition. May I have a suggest? Maybe we could give users a right to set the playing time as they wish, if they are busy and can play only "quick-play" type.

**Comment by Naopod** [comment]
> This is a very interesting proposition. May I have a suggest? Maybe we could give users a right to set the playing time as they wish, if they are busy and can play only "quick-play" type.

This can be an option. You can try implementing it if you want

**Comment by Matthieu-z-David** [comment]
@Naopod I resolve your conflict, please be careful when PR ;)

**Comment by Naopod** [comment]
> @Naopod I resolve your conflict, please be careful when PR ;)

thank you

**Pull request merged**
